# Generated by Django 2.2.1 on 2019-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=50)),
                ('small_description', models.CharField(max_length=500)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('votes', models.IntegerField(default=0)),
                ('big_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='BigDescritpion',
        ),
        migrations.DeleteModel(
            name='SmallDescription',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
